### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by garethhurley** [zbazztian/filter-sarif#3]
Hi @zbazztian 
While the globber module is covered by the Apache 2.0 license there is no explicitly declared license for the overall filter-sarif project.

Could you clarify the overall license of this work?  It is currently unclear whether contributions, redistribution etc. are encouraged or even permitted.

I would suggest using Apache 2.0 to cover the whole work (or the compatible MIT license).

**Comment by zbazztian** [comment]
@garethhurley Thanks, I have added a license (Apache 2.0).
